"""init

Revision ID: 1a8b6e5ce77d
Revises:
Create Date: 2025-12-11 01:09:49.946229

"""

from collections.abc import Sequence

# revision identifiers, used by Alembic.
revision: str = "1a8b6e5ce77d"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
